### ISSUE TITLE
Ablity to set default duckiebot_name

### ISSUE THREAD

**Issue by rgreen32** [duckietown/duckietown-shell#78]
I think having the ability to set a default duckiebot name would be nice. I think a lot of people like myself are only going to work with a single duckiebot so having to specify a **duckiebot_name** for every dts command is needlessly redundant.

**Comment by afdaniele** [comment]
Many dts commands are implemented so that if you don't pass a duckiebot name, that command is run on the host, for example `dts devel build/run`, `dts cli`, etc. 
Adding what you are suggesting would introduce a third behavior that can create confusion. 
Being bored is better than being confused. :slightly_smiling_face:
